### ISSUE TITLE
cmake build doesn't install the same files as GNU tools does

### ISSUE THREAD

**Issue by yurivict** [opencollab/arpack-ng#205]
```
===> Checking for items in STAGEDIR missing from pkg-plist
Error: Orphaned: include/arpack/arpackdef.h
Error: Orphaned: lib/cmake/arpack-ng-config-version.cmake
Error: Orphaned: lib/cmake/arpack-ng-config.cmake
===> Checking for items in pkg-plist which are not in STAGEDIR
Error: Missing: include/arpack/arpack.h
Error: Missing: include/arpack/arpack.hpp
Error: Missing: include/arpack/debug_c.h
Error: Missing: include/arpack/debug_c.hpp
Error: Missing: include/arpack/parpack.h
Error: Missing: include/arpack/parpack.hpp
Error: Missing: include/arpack/stat_c.h
Error: Missing: include/arpack/stat_c.hpp
Error: Missing: lib/libparpack.so
Error: Missing: lib/libparpack.so.2
Error: Missing: lib/libparpack.so.2.1.0
Error: Missing: libdata/pkgconfig/arpack.pc
===> Error: Plist issues found.
```

I would much rather prefer cmake, but it has to install the same files.

**Comment by fghoussen** [comment]
Not familiar with bsd. Just to make sure: do you use some package manager ? or do you git-clone the github repo and build from source with configure or cmake ?

**Comment by yurivict** [comment]
It downloads the tarball from github, and builds from it.

**Comment by yurivict** [comment]
8840cfd builds w/out a problem.

**Comment by fghoussen** [comment]
Don't get what you mean.

When #207 and #203 are both merged, you get the same install with autotools : 

```
>> ./bootstrap; ./configure --enable-icb --enable-mpi --prefix=/tmp/autotools; make all install; tree /tmp/autotools
/tmp/autotools
├── include
│   └── arpack
│       ├── arpackdef.h
│       ├── arpack.h
│       ├── arpack.hpp
│       ├── debug_c.h
│       ├── debug_c.hpp
│       ├── debug.h
│       ├── parpack.h
│       ├── parpack.hpp
│       ├── stat_c.h
│       ├── stat_c.hpp
│       └── stat.h
└── lib
    ├── cmake
    │   ├── arpack-ng-config.cmake
    │   └── arpack-ng-config-version.cmake
    ├── libarpack.a
    ├── libarpack.la
    ├── libarpack.so -> libarpack.so.2.1.0
    ├── libarpack.so.2 -> libarpack.so.2.1.0
    ├── libarpack.so.2.1.0
    ├── libparpack.a
    ├── libparpack.la
    ├── libparpack.so -> libparpack.so.2.1.0
    ├── libparpack.so.2 -> libparpack.so.2.1.0
    ├── libparpack.so.2.1.0
    └── pkgconfig
        └── arpack.pc
```

Than the one you get with cmake : 

```
>> mkdir build; cd build; cmake -DICB=ON -DMPI=ON -DCMAKE_INSTALL_PREFIX=/tmp/cmake ..; make all install; tree /tmp/cmake
/tmp/cmake
├── include
│   └── arpack
│       ├── arpackdef.h
│       ├── arpack.h
│       ├── arpack.hpp
│       ├── debug_c.h
│       ├── debug_c.hpp
│       ├── debug.h
│       ├── parpack.h
│       ├── parpack.hpp
│       ├── stat_c.h
│       ├── stat_c.hpp
│       └── stat.h
└── lib
    ├── cmake
    │   ├── arpack-ng-config.cmake
    │   └── arpack-ng-config-version.cmake
    ├── libarpack.a
    └── libparpack.a

```

**Comment by fghoussen** [comment]
Maybe you use a "port" (I don't know what that is ) and this is buggy. If you do thing by hand, you should get something OK if you have a recent enough (icb support) compiler

**Comment by fghoussen** [comment]
BTW, the best thing would be to add a CI build for FreeBSD.

Seems it's unfortunately impossible to do that with a docker-run ran from an ubuntu host provided by TravisCI. To run FreeBSD inside docker, it seems the host must be FreeBSD ! This limitation (as far as I understand) is due to the fact that the kernel used by FreeBSD is not compatible with the ones used by ubuntu/debian/fedora. Some jetpack project try to make it possible but it's experimental : no great for CI !

If I got it well, Jenkins offers free CI for open-source project, and, seems to provide a FreeDSB build : @sylvestre , you may want to have a look at that ?... Not sure I got it all understood well, and, not sure how this could work... Here is a pointer: https://ci.freebsd.org/

Cirrus-CI looks more like TravisCI and seems to offer FreeBSD :  https://cirrus-ci.org/guide/FreeBSD/

Also, you may have a look at  qemu : http://erouault.blogspot.com/2016/09/running-freebsd-in-travis-ci.html (not tested myself)

**Comment by fghoussen** [comment]
Cirrus-CI seems to allow also for windows

**Comment by fghoussen** [comment]
See #358

**Comment by fghoussen** [comment]
Can this issue be closed?
