### ISSUE TITLE
arpack ng install problem on windows with intel

### ISSUE THREAD

**Issue by ChrisNabold** [opencollab/arpack-ng#226]
I tried to install arpack ng (with latest download) using 
cmake -D EXAMPLES=ON -D MPI=ON -D BUILD_SHARED_LIBS=ON ..
[CMakeError.log](https://github.com/opencollab/arpack-ng/files/3487050/CMakeError.log)
[CMakeOutput.log](https://github.com/opencollab/arpack-ng/files/3487051/CMakeOutput.log)
How can I manage that cmake is using intel mkl with sgem ..
Thank you for your help

**Comment by fghoussen** [comment]
Did you try `export BLA_VENDOR=Intel` but running cmake ? (restart from scratch)
https://cmake.org/cmake/help/v3.14/module/FindBLAS.html

**Comment by ChrisNabold** [comment]
Dear Frank

 

Thank you for your info, I appreciate your help.

I tried it but I still get the same error message.

 

How can I pass the address of the intel MKL library somewhere in the arpack library? Do I have to set any parameters beore call ing cmake?

 

Thank you for your help

 

Best regards

Chris Nabold

**Comment by fghoussen** [comment]
You may give a try to ICB as the problem seems to occur at linking time :

> testFortranCompiler.obj : error LNK2019: unresolved external symbol _SGEMM referenced in function _MAIN__

Fortran compiler may produce symbols like `_SGEMM` or `SGEMM_` or `SGEMM__` : Fortran norm does not specify this, so, nobody knows how to figure out... ICB is meant to deal with that (and other interoperability related problems).

If you want to use cmake, you may try:

> ~/BUILD> BLA_VENDOR=Intel_64lp cmake -DICB=ON .. (run from scratch - I suppose you want lp, not ilp)

If this does not work you should open an issue to cmake : this is a cmake problem or a cmake misuse (which may imply to change arpack-ng/CMakeLists.txt).

If you need a back-up solution, you may give a try to autotools : 

- check out "test arpack with sequential ILP64 MKL assuming you use gnu compilers" in README.md

- check out : https://software.intel.com/en-us/articles/intel-mkl-link-line-advisor

- finally you would end up with something like (I suppose you want lp64, not ilp64 and using intel compilers - not tested : just the spirit of it - you may try with and without ICB)

> LIBS='-Wl,--no-as-needed -lmkl_sequential -lmkl_core -lpthread -lm -ldl' ./configure --with-blas=mkl_lp64 --with-lapack=mkl_lp64 --enable-icb

Finally, it seems you want multi-threaded `lp64` : you need to have installed pthread.h which seems not to be found. So you need before all to install it. Something like this should do it:

> sudo apt-get install libc-dev (debian)

If you don't want multi-threaded, use `lp64_seq` instead of `lp64` (as intel link advisor will tell you).

**Comment by fghoussen** [comment]
possible alternative : #303

**Comment by dariomangoni** [comment]
@ChrisNabold I think you have been misleaded by the CMake error log: it's completely normal to have sgemm test failing on Intel MKL libraries; you do not have to worry about that. It's just a check: your CMake is running just fine.

What you have to do is to set up the proper environmental variables for Intel MKL and to do that the best way is to use the _Intel oneApi command prompt for Intel x64 for Visual Studio_ (or whatever other custom command prompt your MKL version is offering to you).

Please give a look at my answer at issue #283 to have a brief guide. It works also with ICB.

**Comment by fghoussen** [comment]
Documentation has been provided here: https://github.com/opencollab/arpack-ng#windows-support
