### ISSUE TITLE
Why doesn't arpack-ng reimplement the original arpack in Fortran90 or newer?

### ISSUE THREAD

**Issue by hongyi-zhao** [opencollab/arpack-ng#308]
Given that this project is called `arpack-ng`, why not re-implement the original `arpack` in modern Fortran90 or later, instead of the archaic Fortran77?

Regards,
HY

**Comment by zerothi** [comment]
I guess time constraints is the biggest issue. :)
As always it takes a considerable amount of time to re-implement + thoroughly test it. Especially if the interfaces will change.

**Comment by fghoussen** [comment]
`arpack` stands for being the reference code for computing eigen values/vectors in all kind of cases/flavours but it's old (70's f77) and no more maintained (= a pain to compile on modern archs) : `arpack-ng` is "just" a fork that aims at getting things to work on modern archs (no dev, maintain only).

Re-writting `arpack` would be tricky/buggy (computing eigen values is a difficult problem), heavy/long/ungrateful work and even more difficult to justify, fund and validate for people to trust it (`arpack` is used for 50+ years so everybody knows and trust it, and, trust is the key - can you fund a 3 years PhD only to rewrite `arpack` with nothing new but for fun ? no !... And even so, nobody would trust the result because you can't justify 50+ years of correct results !). Same thing for `blas`, `lapack`  or `scalapack` : there all are reference that nobody can afford or want to rewrite : so you just still use all of them !

Rewrite exist : `arpack++`, `slepc` (that embeds `arpack`) , `feast` and `pfeast`, may be also parts of `eigen` (not sure if `eigen` does use or not `arpack`) allow to compute eigen values/vectors but are not considered as the reference, they are considered as initiatives or research works.

**Comment by hongyi-zhao** [comment]
> Same thing for `blas`, `lapack` or `scalapack` : there all are reference that nobody can afford or want to rewrite : so you just still use all of them !

Is this also true for the implementation in intel MKL?

**Comment by RyanBernX** [comment]
In short, there is no need to re-implement a [reference implementation](https://en.wikipedia.org/wiki/Reference_implementation).

When we are talking about BLAS, we are referring to the version maintained by netlib. Strictly speaking, MKL is not a re-implementation of BLAS, yet it is just a commercial-grade implementation which meets the interface standards of BLAS. The netlib BLAS is not suitable for the production purpose. However it is still there, serving as the benchmark of other implementations.

ARPACK has similar roles. When newer algorithms are created, ARPACK can be used to justify the results. According to my limited experiences, there are many eigenvalue solvers that  are faster, but less stable than ARPACK. Thus correctness is the No.1 rule. Whether to implement in a newer version of FORTRAN depends on time and people's interest.

**Comment by hongyi-zhao** [comment]
Another issue pertinent to this issue:

As we all know, intel MKL supplies the Fortran 95 interfaces: BLAS95 or LAPACK95. Does this mean that they are interfaces which help userland Fotran95 source codes be bridged to use the standard BLAS and LAPACK reference implementations written in earlier Fortran versions?
