### ISSUE TITLE
`make check` failed for static compilation

### ISSUE THREAD

**Issue by MacroUniverse** [opencollab/arpack-ng#386]
## Expected behavior

`make check` will pass after `make` after static compilation.

## Actual behavior

`make check` returned compilation error.

## Where/how to reproduce the problem

- arpack-ng: 3.8.0 tag
- OS: ubuntu 18.04
- compiler: gcc (default version)
- environment: 
- configure: ./configure --prefix=$INSTALL_DIR/arpack32-a --enable-static=yes --enable-shared=no

**Comment by sylvestre** [comment]
what is the error ?

**Comment by fghoussen** [comment]
@MacroUniverse: feel free to PR a fix if you got one.

**Comment by fghoussen** [comment]
Working at my side (debian):
```
>> ./bootstrap
>>  ./configure  --enable-static=yes
>> make all check
```

**Comment by fghoussen** [comment]
@MacroUniverse: I guess autotools fails because you probably should have ran `./configure --prefix=$INSTALL_DIR --enable-static=yes --enable-shared=no` instead of `./configure --prefix=$INSTALL_DIR/arpack32-a --enable-static=yes --enable-shared=no` (prefix must point at a directory). Fell free to reopen the issue if this does not fix the problem.
