### ISSUE TITLE
Creating CI job for windows using vcpkg (github action)?

### ISSUE THREAD

**Issue by fghoussen** [opencollab/arpack-ng#427]
## Expected behavior

Creating CI job for windows using vcpkg (github action)?
Seems vcpkg could be integrated in CI: https://github.com/marketplace/actions/vcpkg-action

## Actual behavior

CI has only one job to test arpack-ng on windows using mingw.

## Notes, remarks

@FabienPean: would be nice if you could have a look some day?!... Otherwise let it on the wishlist!

**Comment by FabienPean** [comment]
vcpkg internally uses msys2-mingw package to build arpack-ng, at least in default configuration when no Fortran compiler is available on path (like intel but I never tried), it just streamlines the installation because it is just a package manager after all. Arpack via vcpkg is rather limited as I just brought the default features then (i.e. no parpack, nor int64). There are no tests of apt packages in the CI so I am not sure what are the expectations here ?

**Comment by fghoussen** [comment]
> vcpkg internally uses msys2-mingw

Didn't know!

> what are the expectations here

Adding more tests on more arch if possible. Sounds it's not, so we can likely close this. If it is, reopen it!
