### ISSUE TITLE
No reduction in iterations when supplying a starting vector to dsaupd

### ISSUE THREAD

**Issue by ThomasPKelly** [opencollab/arpack-ng#55]
Hi,

I'm not sure if this is an issue, or I am misunderstanding how starting vectors are applied.

Running dsdrv1 by default supplies me with a set of m eigenvectors after X major iterations. I figured if I used these vectors as initial guesses in a new dsdrv1 run on the same eigenvalue problem, the number of iterations would be dramatically reduced. I found [this documentation](http://www.caam.rice.edu/software/ARPACK/UG/node29.html) on starting vectors, which recommends using the first column of v (the first eigenvector) as a starting vector.

This does indeed result in fewer iterations (down from 150 or so to 16), but only if nev (the number of eigenvectors/eigenvalues desired) is set to 1. If nev > 1, no reduction in iterations occurs.

I ask because I am using arpack to solve a set of nearly-identical eigenvalue problems, and would like to use the results from one as a starting point for another. Does arpack facilitate this when nev > 1?

Thanks

**Comment by caliarim** [comment]
Dear Thomas, I would like to try to reproduce. Can you attach a full example?

**Comment by caliarim** [comment]
Dear Thomas, I can reproduce the behaviour you described, but I do not think it is a bug in arpack. In fact, by taking a previous eigenvector as initial vector, I cannot see how convergence to the other eigenvectors might be improved (you may think to the classical powers method: if you take an eigenvector as initial vector, you have no possibility to converge to any other eigenvector). In the documentation you found, it is written that it is possible to take a linear combination of the previous vectors. I did it (I took the sum of the previous four eigenvectors), and convergence for nev=4 is now reached in about 90 iterations instead of about 150. I attach my code.
[dsdrv1.zip](https://github.com/opencollab/arpack-ng/files/695552/dsdrv1.zip)

**Comment by ThomasPKelly** [comment]
Hi,

Thank you for the reply. I think you are right that it is not a bug. Though
strangely I have not been able to reproduce your reduction in iterations
with my own code (implying it is a bug in my own code). I'll attach it in
case you are interested, but I will take a close look at your code.

Thanks again,
Thomas

**Comment by caliarim** [comment]
I do not see your attachment.

**Comment by ThomasPKelly** [comment]
Apologies, here is the attachment.
https://www.dropbox.com/s/8axiu58bub4qhak/dsdrv1_test.f?dl=0

**Comment by caliarim** [comment]
Dear Thomas,

you forgot to initialize resid to 0 in the if ( restart ) then branch.

**Comment by caliarim** [comment]
Is it possible to close this open issue?

**Comment by sylvestre** [comment]
Sure, thanks
